### ISSUE TITLE
Errors about "undefined method `split' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by macarima** [wurmlab/NpSearch#1]
Hello,

I installed NpSearch on 3 linux workstations, and got errors about "undefined method `split' for nil:NilClass (NoMethodError)".
They installed version 2.1.4 and 2.1.5 on ruby 2.4.0 (ubuntu 14.04)

2 of them sent error messages like below when I test NpSearch with protein.fa from test directory.

```
npsearch -n 40 -d protein.fa > debug.log 
/var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/scoresequence.rb:81:in `np_similarity': undefined method `split' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/scoresequence.rb:17:in `run'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch.rb:87:in `initialise_seqs'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch.rb:73:in `block (2 levels) in iterate_input_file'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/pool.rb:37:in `block (4 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/pool.rb:35:in `loop'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/pool.rb:35:in `block (3 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/pool.rb:34:in `catch'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.5/lib/npsearch/pool.rb:34:in `block (2 levels) in initialize'
```

and... 1 of them sent error message like this.

```
npsearch -n 48 /var/lib/gems/2.4.0/gems/npsearch-2.1.4/test/files/protein.fa 
/var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/sequence.rb:22:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch.rb:86:in `new'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch.rb:86:in `initialise_seqs'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch.rb:73:in `block (2 levels) in iterate_input_file'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/pool.rb:37:in `block (4 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/pool.rb:35:in `loop'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/pool.rb:35:in `block (3 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/pool.rb:34:in `catch'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.4/lib/npsearch/pool.rb:34:in `block (2 levels) in initialize'
```

and... let you show debug file.

```
D, [2017-01-25T23:58:22.382356 #36456] DEBUG -- : Testing if the input fasta file exists: 'protein.fa'.
D, [2017-01-25T23:58:22.382423 #36456] DEBUG -- : Testing if the input file ('/home/macarima/bioapps/npsearch/test/files/protein.fa') is empty.
D, [2017-01-25T23:58:22.382449 #36456] DEBUG -- : Testing whether the input, ('/home/macarima/bioapps/npsearch/test/files/protein.fa') is a fasta file.
D, [2017-01-25T23:58:22.382487 #36456] DEBUG -- : Checking the type of sequence in the input file based on the first 500 lines.
D, [2017-01-25T23:58:22.424464 #36456] DEBUG -- :  The guessed typed of Sequences are: [:protein]
D, [2017-01-25T23:58:22.424499 #36456] DEBUG -- : Checking the number of threads: 40
D, [2017-01-25T23:58:22.424515 #36456] DEBUG -- : Checking SignalP 4.1 Script binary at: signalp.
D, [2017-01-25T23:58:22.426889 #36456] DEBUG -- : The validated OPT hash contains: {:signalp_path=>"signalp", :temp_dir=>"/home/macarima/bioapps/npsearch/test/files/.temp/20170125-36456-13j2yn2", :num_threads=>40, :debug=>true, :min_orf_length=>30, :max_orf_length=>600, :input_file=>"/home/macarima/bioapps/npsearch/test/files/protein.fa", :type=>:protein}
D, [2017-01-25T23:58:22.426921 #36456] DEBUG -- : Creating a thread pool of size 40
D, [2017-01-25T23:58:22.432482 #36456] DEBUG -- : Successfully creating temp directory at: /home/macarima/bioapps/npsearch/test/files/.temp/20170125-36456-13j2yn2
D, [2017-01-25T23:58:22.432537 #36456] DEBUG -- : Iterating the Input File: /home/macarima/bioapps/npsearch/test/files/protein.fa
D, [2017-01-25T23:58:22.466209 #36456] DEBUG -- : -- Analysing: 'isotig00001_f1' (728)
D, [2017-01-25T23:58:22.466325 #36456] DEBUG -- : -- Analysing: 'isotig00001_f2' (728)
D, [2017-01-25T23:58:22.466379 #36456] DEBUG -- : -- Analysing: 'isotig00001_f3' (727)
D, [2017-01-25T23:58:22.466426 #36456] DEBUG -- : -- Analysing: 'isotig00001_f4' (728)
D, [2017-01-25T23:58:22.466511 #36456] DEBUG -- : -- Analysing: 'isotig00001_f5' (728)
D, [2017-01-25T23:58:22.466554 #36456] DEBUG -- : -- Analysing: 'isotig00001_f6' (727)
D, [2017-01-25T23:58:22.466594 #36456] DEBUG -- : -- Analysing: 'isotig00002_f1' (638)
D, [2017-01-25T23:58:22.466632 #36456] DEBUG -- : -- Analysing: 'isotig00002_f2' (637)
D, [2017-01-25T23:58:22.466675 #36456] DEBUG -- : -- Analysing: 'isotig00002_f3' (637)
D, [2017-01-25T23:58:22.466714 #36456] DEBUG -- : -- Analysing: 'isotig00002_f4' (638)
D, [2017-01-25T23:58:22.466753 #36456] DEBUG -- : -- Analysing: 'isotig00002_f5' (637)
D, [2017-01-25T23:58:22.466794 #36456] DEBUG -- : -- Analysing: 'isotig00002_f6' (637)
D, [2017-01-25T23:58:22.466833 #36456] DEBUG -- : -- Analysing: 'isotig00003_f1' (639)
D, [2017-01-25T23:58:22.466875 #36456] DEBUG -- : -- Analysing: 'isotig00003_f2' (638)
D, [2017-01-25T23:58:22.466913 #36456] DEBUG -- : -- Analysing: 'isotig00003_f3' (638)
D, [2017-01-25T23:58:22.466955 #36456] DEBUG -- : -- Analysing: 'isotig00003_f4' (639)
D, [2017-01-25T23:58:22.466998 #36456] DEBUG -- : -- Analysing: 'isotig00003_f5' (638)
D, [2017-01-25T23:58:22.467037 #36456] DEBUG -- : -- Analysing: 'isotig00003_f6' (638)
D, [2017-01-25T23:58:22.467078 #36456] DEBUG -- : -- Analysing: 'isotig00004_f1' (632)
D, [2017-01-25T23:58:22.467116 #36456] DEBUG -- : -- Analysing: 'isotig00004_f2' (631)
D, [2017-01-25T23:58:22.467157 #36456] DEBUG -- : -- Analysing: 'isotig00004_f3' (631)
D, [2017-01-25T23:58:22.467216 #36456] DEBUG -- : -- Analysing: 'isotig00004_f4' (632)
D, [2017-01-25T23:58:22.467254 #36456] DEBUG -- : -- Analysing: 'isotig00004_f5' (631)
D, [2017-01-25T23:58:22.467299 #36456] DEBUG -- : -- Analysing: 'isotig00004_f6' (631)
D, [2017-01-25T23:58:22.467337 #36456] DEBUG -- : -- Analysing: 'isotig00005_f1' (596)
D, [2017-01-25T23:58:22.468225 #36456] DEBUG -- : -- Analysing: 'isotig00005_f2' (596)
D, [2017-01-25T23:58:22.469046 #36456] DEBUG -- : -- Analysing: 'isotig00005_f3' (595)
D, [2017-01-25T23:58:22.469902 #36456] DEBUG -- : -- Analysing: 'isotig00005_f4' (596)
D, [2017-01-25T23:58:22.471054 #36456] DEBUG -- : -- Analysing: 'isotig00005_f5' (596)
D, [2017-01-25T23:58:22.471460 #36456] DEBUG -- : -- Analysing: 'isotig00005_f6' (595)
D, [2017-01-25T23:58:22.471841 #36456] DEBUG -- : -- Analysing: 'isotig00006_f1' (582)
D, [2017-01-25T23:58:22.472240 #36456] DEBUG -- : -- Analysing: 'isotig00006_f2' (582)
D, [2017-01-25T23:58:22.472692 #36456] DEBUG -- : -- Analysing: 'isotig00006_f3' (581)
D, [2017-01-25T23:58:22.473142 #36456] DEBUG -- : -- Analysing: 'isotig00006_f4' (582)
D, [2017-01-25T23:58:22.473532 #36456] DEBUG -- : -- Analysing: 'isotig00006_f5' (582)
D, [2017-01-25T23:58:22.473856 #36456] DEBUG -- : -- Analysing: 'isotig00006_f6' (581)
D, [2017-01-25T23:58:22.474214 #36456] DEBUG -- : -- Analysing: 'isotig00007_f1' (583)
D, [2017-01-25T23:58:22.475931 #36456] DEBUG -- : -- Analysing: 'isotig00007_f2' (582)
D, [2017-01-25T23:58:22.476318 #36456] DEBUG -- : -- Analysing: 'isotig00007_f3' (582)
D, [2017-01-25T23:58:22.476752 #36456] DEBUG -- : -- Analysing: 'isotig00007_f4' (583)
D, [2017-01-25T23:58:22.477174 #36456] DEBUG -- : -- Analysing: 'isotig00007_f5' (582)
D, [2017-01-25T23:58:22.477546 #36456] DEBUG -- : -- Analysing: 'isotig00007_f6' (582)
D, [2017-01-25T23:58:22.477936 #36456] DEBUG -- : -- Analysing: 'isotig00008_f1' (575)
D, [2017-01-25T23:58:22.478290 #36456] DEBUG -- : -- Analysing: 'isotig00008_f2' (575)
D, [2017-01-25T23:58:22.478687 #36456] DEBUG -- : -- Analysing: 'isotig00008_f3' (574)
D, [2017-01-25T23:58:22.479812 #36456] DEBUG -- : -- Analysing: 'isotig00008_f4' (575)
D, [2017-01-25T23:58:22.480164 #36456] DEBUG -- : -- Analysing: 'isotig00008_f5' (575)
D, [2017-01-25T23:58:22.480627 #36456] DEBUG -- : -- Analysing: 'isotig00008_f6' (574)
D, [2017-01-25T23:58:22.481044 #36456] DEBUG -- : -- Analysing: 'isotig00009_f1' (609)
D, [2017-01-25T23:58:22.481130 #36456] DEBUG -- : -- Analysing: 'isotig00009_f2' (608)
D, [2017-01-25T23:58:22.481204 #36456] DEBUG -- : -- Analysing: 'isotig00009_f3' (608)
D, [2017-01-25T23:58:22.481262 #36456] DEBUG -- : -- Analysing: 'isotig00009_f4' (609)
D, [2017-01-25T23:58:22.481308 #36456] DEBUG -- : -- Analysing: 'isotig00009_f5' (608)
D, [2017-01-25T23:58:22.481350 #36456] DEBUG -- : -- Analysing: 'isotig00009_f6' (608)
D, [2017-01-25T23:58:22.481396 #36456] DEBUG -- : -- Analysing: 'isotig00010_f1' (550)
D, [2017-01-25T23:58:22.481753 #36456] DEBUG -- : -- Analysing: 'isotig00010_f2' (549)
D, [2017-01-25T23:58:22.484191 #36456] DEBUG -- : -- Analysing: 'isotig00010_f3' (549)
D, [2017-01-25T23:58:22.484589 #36456] DEBUG -- : -- Analysing: 'isotig00010_f4' (550)
D, [2017-01-25T23:58:22.484896 #36456] DEBUG -- : -- Analysing: 'isotig00010_f5' (549)
D, [2017-01-25T23:58:22.485227 #36456] DEBUG -- : -- Analysing: 'isotig00010_f6' (549)
D, [2017-01-25T23:58:22.485597 #36456] DEBUG -- : -- Analysing: 'isotig00011_f1' (508)
D, [2017-01-25T23:58:22.485976 #36456] DEBUG -- : -- Analysing: 'isotig00011_f2' (508)
D, [2017-01-25T23:58:22.486399 #36456] DEBUG -- : -- Analysing: 'isotig00011_f3' (507)
D, [2017-01-25T23:58:22.486883 #36456] DEBUG -- : -- Analysing: 'isotig00011_f4' (508)
D, [2017-01-25T23:58:22.487421 #36456] DEBUG -- : -- Analysing: 'isotig00011_f5' (508)
D, [2017-01-25T23:58:22.509613 #36456] DEBUG -- : -- Analysing: 'isotig00011_f6' (507)
D, [2017-01-25T23:58:22.510061 #36456] DEBUG -- : -- Analysing: 'isotig00012_f1' (494)
D, [2017-01-25T23:58:22.510448 #36456] DEBUG -- : -- Analysing: 'isotig00012_f2' (494)
D, [2017-01-25T23:58:22.511015 #36456] DEBUG -- : -- Analysing: 'isotig00012_f3' (493)
D, [2017-01-25T23:58:22.511459 #36456] DEBUG -- : -- Analysing: 'isotig00012_f4' (494)
D, [2017-01-25T23:58:23.045235 #36456] DEBUG -- : -- Analysing: 'isotig00012_f5' (494)
D, [2017-01-25T23:58:23.143812 #36456] DEBUG -- : -- Analysing: 'isotig00012_f6' (493)
D, [2017-01-25T23:58:23.199483 #36456] DEBUG -- : -- Analysing: 'isotig00013_f1' (495)
D, [2017-01-25T23:58:23.278123 #36456] DEBUG -- : -- Analysing: 'isotig00013_f2' (494)
D, [2017-01-25T23:58:23.279007 #36456] DEBUG -- : -- Analysing: 'isotig00013_f3' (494)
D, [2017-01-25T23:58:23.279429 #36456] DEBUG -- : -- Analysing: 'isotig00013_f4' (495)
D, [2017-01-25T23:58:23.287377 #36456] DEBUG -- : -- Analysing: 'isotig00013_f5' (494)
D, [2017-01-25T23:58:23.299540 #36456] DEBUG -- : -- Analysing: 'isotig00013_f6' (494)
D, [2017-01-25T23:58:23.301906 #36456] DEBUG -- : -- Analysing: 'isotig00014_f1' (486)
D, [2017-01-25T23:58:23.302219 #36456] DEBUG -- : -- Analysing: 'isotig00014_f2' (486)
D, [2017-01-25T23:58:23.302388 #36456] DEBUG -- : -- Analysing: 'isotig00014_f3' (485)
D, [2017-01-25T23:58:23.303625 #36456] DEBUG -- : -- Analysing: 'isotig00014_f4' (486)
D, [2017-01-25T23:58:23.309871 #36456] DEBUG -- : -- Analysing: 'isotig00014_f5' (486)
D, [2017-01-25T23:58:23.312765 #36456] DEBUG -- : -- Analysing: 'isotig00014_f6' (485)
D, [2017-01-25T23:58:23.321314 #36456] DEBUG -- : -- Analysing: 'isotig00015_f1' (379)
D, [2017-01-25T23:58:23.323473 #36456] DEBUG -- : -- Analysing: 'isotig00015_f2' (379)
D, [2017-01-25T23:58:23.328402 #36456] DEBUG -- : -- Analysing: 'isotig00015_f3' (378)
D, [2017-01-25T23:58:23.329827 #36456] DEBUG -- : -- Analysing: 'isotig00015_f4' (379)
D, [2017-01-25T23:58:23.348442 #36456] DEBUG -- : -- Analysing: 'isotig00015_f5' (379)
D, [2017-01-25T23:58:23.363302 #36456] DEBUG -- : -- Analysing: 'isotig00015_f6' (378)

```

What's wrong about this situation?
Thank you for your help.

Best,
Hui-Su Kim.

**Comment by IsmailM** [comment]
Hey Hui-Su Kim,

Apologies for the error.

This bug is due to the presence of `*` in the protein file. The test file - `test/files/protein.fa` is just there for unit testing and is not meant to be used by end-users (the file is used to test the individual methods inside npsearch).

It is assumed that the input file would either contain genetic data (which is then translated in all 6 frames and ORF extracted) or alternatively, would contain protein data (where the entire sequence is assumed to be the ORF)...

I have updated the npsearch to skip the sequence if it contains illegal characters (such as `*`). So it should 

Also have just noticed that `exemplar_data/protein.fa` contains transcriptome data and not protein data - I've updated that with a subset of some protein data from Aplysia californica (half of the sequence are from the top half of the actual NpSearch results, and other half are random sequences from the dataset). (I haven't looked at it before - some interesting stuff there btw)...

On a side note, you haven't linked the signalp script (command line argument option `-s`)...

Also wanted to make sure you are aware that, being a beta app, there are some issues with the multi-threading - it calls a lot more threads than requested, and works on a large number of temporary files; which can cause issues on much larger input files. I'll work on these issues when I get chance....

SO..

In order to use the updated version of the app, please run the following:
```
gem uninstall npsearch
gem install npsearch 

# copy protein fasta file to a local folder
cp /var/lib/gems/2.4.0/gems/npsearch-2.1.6/exemplar_data/protein.fa  protein.fa

# run npsearch 
npsearch -s /path/to/signalp/script -n 40 protein.fa
```
Alternatively, download the source code from this repository and copy the  `protein.fa` file (form the exemplar_data folder) into your working directory.

Let me know if you have any further questions or feedback. thanks
Kind Regards, 
IsmailM

**Comment by macarima** [comment]
Thank you for your fast answer.

I tried to update NpSearch, but I still got some errors.
And SignalP is in path, so I don't need to set option '-s'.

2 of them sent this error.

```
npsearch -n 16 protein.fa 
(__TEMPLATE__):53:in `block in singleton class': uninitialized constant NpSearch::VERSION (NameError)
	from (__TEMPLATE__):-2:in `instance_eval'
	from (__TEMPLATE__):-2:in `singleton class'
	from (__TEMPLATE__):-4:in `__tilt_10533840'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch/output.rb:12:in `to_html'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:36:in `run'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/bin/npsearch:91:in `<top (required)>'
	from /usr/local/bin/npsearch:22:in `load'
	from /usr/local/bin/npsearch:22:in `<main>'
```

and 1 of them sent this error.

```
npsearch -s /usr/local/bin/signalp test.fa 
/var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch/sequence.rb:22:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:86:in `new'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:86:in `initialise_seqs'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:75:in `block in iterate_input_file'
	from /var/lib/gems/2.4.0/gems/bio-1.5.1/lib/bio/io/flatfile.rb:336:in `each_entry'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:71:in `iterate_input_file'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/lib/npsearch.rb:33:in `run'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.6/bin/npsearch:91:in `<top (required)>'
	from /usr/local/bin/npsearch:22:in `load'
	from /usr/local/bin/npsearch:22:in `<main>'
```

Thank you for your help.


Best,
Hui-Su Kim

**Comment by IsmailM** [comment]
Apologies...

I just released another update. Please run the following:

```
gem uninstall npsearch
gem install npsearch 

# Check NpSearch version (should be 2.1.7)
npsearch --version 

# run npsearch 
npsearch -s /path/to/signalp/script -n 40 protein.fa
```
I'm hoping that will fix things :) - If not, I'll take a proper look tomorrow.

Let me know how you get on.

**Comment by macarima** [comment]
Thank you for your answer.

I updated npsearch to 2.1.7, but I still got same errors.

```
npsearch -s /usr/local/bin/signalp -d test.fa > debug.log
(__TEMPLATE__):53:in `block in singleton class': uninitialized constant NpSearch::VERSION (NameError)
	from (__TEMPLATE__):-2:in `instance_eval'
	from (__TEMPLATE__):-2:in `singleton class'
	from (__TEMPLATE__):-4:in `__tilt_13073360'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
	from /var/lib/gems/2.4.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/output.rb:12:in `to_html'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch.rb:36:in `run'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/bin/npsearch:91:in `<top (required)>'
	from /usr/local/bin/npsearch:22:in `load'
	from /usr/local/bin/npsearch:22:in `<main>'
```

and...

```
npsearch -n 16 -d Bc_RNASeq_v1.aa.part-2.fa > debug.log
/var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/sequence.rb:22:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch.rb:86:in `new'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch.rb:86:in `initialise_seqs'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch.rb:73:in `block (2 levels) in iterate_input_file'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/pool.rb:37:in `block (4 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/pool.rb:35:in `loop'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/pool.rb:35:in `block (3 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/pool.rb:34:in `catch'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.7/lib/npsearch/pool.rb:34:in `block (2 levels) in initialize'
```

Thank you for your help.
And... I'll set up new workstation for CentOS.
Let you know how it works.


Best,
Hui-Su Kim

**Comment by IsmailM** [comment]
Hey, 

Do you mind updating and trying again? (I just pushed another update)

Also do you mind sending me the log file produced so that I can take a proper look at fixing this...
Thanks,
IsmailM

**Comment by macarima** [comment]
Thank you so much for your fast updates.

I updated npsearch to 2.1.8, and I got 2 success and 1 error.

Here is the message of 1 error.
```
npsearch -n 24 -d test.fa > debug.log
/var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/sequence.rb:22:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch.rb:88:in `new'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch.rb:88:in `initialise_seqs'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch.rb:74:in `block (2 levels) in iterate_input_file'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/pool.rb:37:in `block (4 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/pool.rb:35:in `loop'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/pool.rb:35:in `block (3 levels) in initialize'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/pool.rb:34:in `catch'
	from /var/lib/gems/2.4.0/gems/npsearch-2.1.8/lib/npsearch/pool.rb:34:in `block (2 levels) in initialize'
```

and here is log file.
```
D, [2017-01-26T12:53:43.347938 #12276] DEBUG -- : Testing if the input fasta file exists: 'test.fa'.
D, [2017-01-26T12:53:43.348016 #12276] DEBUG -- : Testing if the input file ('/home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/test.fa') is empty.
D, [2017-01-26T12:53:43.348045 #12276] DEBUG -- : Testing whether the input, ('/home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/test.fa') is a fasta file.
D, [2017-01-26T12:53:43.348083 #12276] DEBUG -- : Checking the type of sequence in the input file based on the first 500 lines.
D, [2017-01-26T12:53:43.357776 #12276] DEBUG -- :  The guessed typed of Sequences are: [:protein]
D, [2017-01-26T12:53:43.357818 #12276] DEBUG -- : Checking the number of threads: 24
D, [2017-01-26T12:53:43.357838 #12276] DEBUG -- : Checking SignalP 4.1 Script binary at: signalp.
D, [2017-01-26T12:53:43.360354 #12276] DEBUG -- : The validated OPT hash contains: {:signalp_path=>"signalp", :temp_dir=>"/home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/.temp/20170126-12276-3jp756", :num_threads=>24, :debug=>true, :min_orf_length=>30, :max_orf_length=>600, :input_file=>"/home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/test.fa", :type=>:protein}
D, [2017-01-26T12:53:43.360453 #12276] DEBUG -- : Creating a thread pool of size 24
D, [2017-01-26T12:53:43.364249 #12276] DEBUG -- : Successfully creating temp directory at: /home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/.temp/20170126-12276-3jp756
D, [2017-01-26T12:53:43.364327 #12276] DEBUG -- : Iterating the Input File: /home/macarima/data/RNASeq_work/Bc/Bc_RNASeq_v1/fasta/test.fa
D, [2017-01-26T12:53:43.400267 #12276] DEBUG -- : -- Analysing: 'Bc_CDS_00001' (156)
D, [2017-01-26T12:53:43.401192 #12276] DEBUG -- : -- Analysing: 'Bc_CDS_00002' (338)
D, [2017-01-26T12:53:43.453179 #12276] DEBUG -- : -- SignalP  : {:name=>"0.000", :cmax=>"1", :cmax_pos=>"0.000", :ymax=>"1", :ymax_pos=>"0.000", :smax=>"1", :smax_pos=>"0.000", :smean=>"0.000", :d=>"N", :sp=>"0.340", :dmaxcut=>"SignalP-noTM", :networks=>"MTELNIEFIKNKLNTTNEDELKNSTDFQFVLLNITAINPSVFGDLFSNLRRVNLNSNAIVTIEPKLFSKLVNLEELGLGFNKIETLSADTFNGLVNLKSLDIGNNQINTIDPKAFEHVVNLEILRLSYNKITSLSEGIFDSLSKLESLSLDGNQLTTLSSNLFEKLINLKGLFLSSNHLTSIDPKTFNTLTKLDTLFLGSNNFTSFDVDTFKLVTNLNKLYLEKNQLETLDPQIFSTLTNLVEIYLFDNKLKKIDPYIFKNLKCLRNILMEHNEIKQDKIELYLPESVTFLIFKDSNNPFYYEQENHLDSVIRPSSISRPTSSKWTSTTRPAIILLHL", :orf=>nil}
```

And NpSearch on CentOS 7 workstation (newly setup) also works well.


Thank you for your help.

Best,
Hui-Su Kim

**Comment by IsmailM** [comment]
Thanks for sending that across.

Looking at the log, the issue seems to be the output from the SignalP script:

Do you mind running the following in the terminal and sending me the output?

```
SEQ=MTELNIEFIKNKLNTTNEDELKNSTDFQFVLLNITAINPSVFGDLFSNLRRVNLNSNAIVTIEPKLFSKLVNLEELGLGFNKIETLSADTFNGLVNLKSLDIGNNQINTIDPKAFEHVVNLEILRLSYNKITSLSEGIFDSLSKLESLSLDGNQLTTLSSNLFEKLINLKGLFLSSNHLTSIDPKTFNTLTKLDTLFLGSNNFTSFDVDTFKLVTNLNKLYLEKNQLETLDPQIFSTLTNLVEIYLFDNKLKKIDPYIFKNLKCLRNILMEHNEIKQDKIELYLPESVTFLIFKDSNNPFYYEQENHLDSVIRPSSISRPTSSKWTSTTRPAIILLHL

echo '>seq\n$SEQ\n' | signalp -t euk -f short -U 0.34 -u 0.34
```

Thanks,
IsmailM

**Comment by macarima** [comment]
Thank you for your fast answer.

The output is below.
```
echo '>seq\n$SEQ\n' | signalp -t euk -f short -U 0.34 -u 0.34
# SignalP-4.1 euk predictions
# name                     Cmax  pos  Ymax  pos  Smax  pos  Smean   D     ?  Dmaxcut    Networks-used
Unable to open(r) file /opt/signalp-4.1/syn/euk.TM.SP/euk.TM.SP.1.A.syn
Unable to open(r) file /opt/signalp-4.1/syn/euk.TM.CS/euk.TM.CS.1.A.syn
Unable to open(r) file /opt/signalp-4.1/syn/euk.noTM.SP/euk.noTM.SP.1.A.syn
Unable to open(r) file /opt/signalp-4.1/syn/euk.noTM.CS/euk.noTM.CS.1.A.syn
                           0.000   1  0.000   1  0.000   1  0.000   0.000 N  0.340      SignalP-noTM
```

So, I re-download the SignalP package and install again.
Now all errors were removed. Thank you so much for your help.


Best,
Hui-Su Kim

**Comment by IsmailM** [comment]
No worries, glad I could be of a help.
